spring.application.name=${SPRING_APPLICATION_NAME:NotesLink}

# --- MySQL datasource ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate dialect
spring.jpa.properties.hibernate.dialect=${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}

# JPA
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${FORMAT_SQL:true}

# Server port
server.port=${PORT:8080}

# Spring Security
spring.security.user.name=${SPRING_SECURITY_USERNAME}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}

# --- HikariCP ---
spring.datasource.hikari.maximum-pool-size=${DB_MAX_POOL_SIZE:10}
spring.datasource.hikari.minimum-idle=${DB_MIN_IDLE:2}

spring.datasource.hikari.max-lifetime=${DB_MAX_LIFETIME:15000}
spring.datasource.hikari.idle-timeout=${DB_IDLE_TIMEOUT:20000}
spring.datasource.hikari.connection-timeout=${DB_CONNECTION_TIMEOUT:30000}

spring.datasource.hikari.validation-timeout=${DB_VALIDATION_TIMEOUT:5000}
spring.datasource.hikari.keepalive-time=${DB_KEEPALIVE_TIME:15000}

# Multipart upload
spring.servlet.multipart.enabled=${MULTIPART_ENABLED:true}
spring.servlet.multipart.max-file-size=${MAX_FILE_SIZE:50MB}
spring.servlet.multipart.max-request-size=${MAX_REQUEST_SIZE:50MB}

# Google OAuth
google.client.id=${GOOGLE_CLIENT_ID}

# Secret Key to Encrypt Drive Link
aes.secret.key=${AES_SECRET_KEY}

# JWT configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}