spring.application.name=NotesLink

# --- MySQL datasource (Hostinger) ---
spring.datasource.url=jdbc:mysql://193.203.184.157:3306/u333291976_noteslink?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=u333291976_global_admin
spring.datasource.password=Rohit987274@

# Hibernate dialect (explicit)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server port
server.port=${PORT:8080}

#Spring Security
spring.security.user.name = rohit
spring.security.user.password = rohit

# --- HikariCP tuning for remote MySQL (Hostinger) ---

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.datasource.hikari.max-lifetime=15000
spring.datasource.hikari.idle-timeout=20000
spring.datasource.hikari.connection-timeout=30000

spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.keepalive-time=15000

# Enable multipart upload
spring.servlet.multipart.enabled=true

# Max file size
spring.servlet.multipart.max-file-size=50MB

# Max request size (file + JSON)
spring.servlet.multipart.max-request-size=50MB

#Google OAuth
google.client.id=180210663874-7c66sclnjrnaterpj1bspgmvb1hmu86r.apps.googleusercontent.com

#Secret Key to Encrypt Drive Link
aes.secret.key=9809150152987274

# JWT configuration
jwt.secret=166256d3c0d0010bd5784967a5315ba575cb4302b4afdc1951710e202cafaed9
jwt.expiration=3600000
